### ISSUE TITLE
Blurry on retina Macbook

### ISSUE THREAD

**Issue by kimballfrank** [penk/terrarium-app#15]
This app is awesome. But it is blurry on retina macbook. Easy fix?

**Comment by cridenour** [comment]
This is actually a real quick fix. 

Open up Terrarium.app/Contents/Info.plist and add 

```
<key>NSPrincipalClass</key>
<string>NSApplication</string>
<key>NSHighResolutionCapable</key>
<string>True</string>
```

Retina support!
